name: test

on: push

jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod

      - name: Run Go build
        run: go build -v ./...

      - name: Run Go tests
        uses: robherley/go-test-action@v1
